sudo: required

language: node_js
node_js:
  - 10

branches:
  only:
    - master

notifications:
  email: false

before_script:
  - npm install
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git checkout --orphan gh-pages
  - git rm --cached -r .
  - touch .nojekyll
  - git add index.html imgs .nojekyll
  - git add -f node_modules/tracking/build/tracking-min.js
  - git add -f node_modules/dat.gui/build/dat.gui.min.js

script:
  - git commit -m "update site"
  - git remote add gh https://$GHTOKEN@github.com/xconf-br-2019/trackerjs-test.git
  - git push gh :gh-pages
  - git push -u gh gh-pages

after_script:
  - git checkout -f master
  - git branch -D gh-pages
